name: olivio
channels:
  - defaults
dependencies:
  - ipykernel
  - notebook
  - pandas
  - numpy
  - plotly
  - matplotlib
  - python-dotenv
  - seaborn
  - openpyxl
  - scikit-learn
  - jupyter
  - pip
  #- pip:
      # Add any pip packages here if necessary.
